services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: predictions_log
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mlflow:
    build:
      context: /home/monarch/ASFOTEC-MLStack-Demo
      dockerfile: infra/docker/mlflow.Dockerfile
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    ports:
      - "5000:5000"
    volumes:
      - ./mlops/artifacts:/mlflow-artifacts
    depends_on:
      - minio

  api:
    build:
      context: /home/monarch/ASFOTEC-MLStack-Demo
      dockerfile: Dockerfile.api
    ports:
      - "8000:8080"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_EXPERIMENT_NAME: ChurnClassifier
      MLFLOW_ARTIFACT_BUCKET: mlflow-artifacts
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      PYTHONPATH: /app
      POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/predictions_log
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LLM_PROVIDER: sherlock
      PORT: 8080
    volumes:
      - ../../chroma_db:/app/chroma_db
      - ../../rag:/app/rag
    depends_on:
      - mlflow
      - postgres
      - kafka

#  kafka-consumer:
#    build:
#      context: /home/monarch/ASFOTEC-MLStack-Demo
#      dockerfile: Dockerfile.api
#    environment:
#      POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/predictions_log
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    depends_on:
#      - postgres
#      - kafka
#    command: python scripts/kafka_consumer.py

volumes:
  postgres_data:
  kafka_data:
  minio_data:
